# Generated by Django 5.2.6 on 2025-11-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='Projects.proyecto')),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventarioMaterial',
            fields=[
                ('id_inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Inventory.inventario')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.material')),
            ],
            options={
                'db_table': 'inventario_material',
                'managed': True,
                'unique_together': {('id_inventario', 'id_material')},
            },
        ),
        migrations.CreateModel(
            name='ProveedorMaterial',
            fields=[
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Inventory.proveedor')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_entrega', models.IntegerField(blank=True, db_comment='Días de entrega', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.material')),
            ],
            options={
                'db_table': 'proveedor_material',
                'managed': True,
                'unique_together': {('id_proveedor', 'id_material')},
            },
        ),
    ]
