# Generated by Django 5.2.6 on 2025-11-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(db_comment='Administrador/Cliente/Supervisor', max_length=50)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='Projects.proyecto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='Core.usuario')),
            ],
            options={
                'db_table': 'usuario_proyecto',
                'managed': True,
                'unique_together': {('id_usuario', 'id_proyecto')},
            },
        ),
    ]
